//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamradt.Parser.Web.Test {
    
    
    public partial class FormulaParserTest {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// TestFormattedFormula control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula TestFormattedFormula;
        
        /// <summary>
        /// AndCondition1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula AndCondition1;
        
        /// <summary>
        /// AndCondition2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula AndCondition2;
        
        /// <summary>
        /// Numerator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula Numerator;
        
        /// <summary>
        /// Denominator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula Denominator;
        
        /// <summary>
        /// LHSEquals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSEquals;
        
        /// <summary>
        /// RHSEquals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSEquals;
        
        /// <summary>
        /// LHSGreaterThan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSGreaterThan;
        
        /// <summary>
        /// RHSGreaterThan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSGreaterThan;
        
        /// <summary>
        /// LHSGreaterThanOrEqual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSGreaterThanOrEqual;
        
        /// <summary>
        /// RHSGreaterThanOrEqual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSGreaterThanOrEqual;
        
        /// <summary>
        /// LHSLessThan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSLessThan;
        
        /// <summary>
        /// RHSLessThan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSLessThan;
        
        /// <summary>
        /// LHSLessThanOrEqual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSLessThanOrEqual;
        
        /// <summary>
        /// RHSLessThanOrEqual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSLessThanOrEqual;
        
        /// <summary>
        /// LHSMinus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSMinus;
        
        /// <summary>
        /// RHSMinus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSMinus;
        
        /// <summary>
        /// LHSMultiply control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSMultiply;
        
        /// <summary>
        /// RHSMultiply control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSMultiply;
        
        /// <summary>
        /// LHSNotEqual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSNotEqual;
        
        /// <summary>
        /// RHSNotEqual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSNotEqual;
        
        /// <summary>
        /// LHSOr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSOr;
        
        /// <summary>
        /// RHSOr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSOr;
        
        /// <summary>
        /// LHSPlus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSPlus;
        
        /// <summary>
        /// RHSPlus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSPlus;
        
        /// <summary>
        /// LHSPower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LHSPower;
        
        /// <summary>
        /// RHSPower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula RHSPower;
        
        /// <summary>
        /// IfCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula IfCondition;
        
        /// <summary>
        /// IfTrue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula IfTrue;
        
        /// <summary>
        /// IfFalse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula IfFalse;
        
        /// <summary>
        /// IfNullCheck control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula IfNullCheck;
        
        /// <summary>
        /// IfNullValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula IfNullValue;
        
        /// <summary>
        /// LenValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula LenValue;
        
        /// <summary>
        /// SubstringValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula SubstringValue;
        
        /// <summary>
        /// SubstringStartIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula SubstringStartIndex;
        
        /// <summary>
        /// SubstringLength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kamradt.Parser.Web.controls.StandardFormattedFormula SubstringLength;
    }
}
